lab 9

Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [10]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Array Indexing")
print(arr[0][2])
print("Fancy Indexing")
print(arr[[0,1],[1,2]])

Array Indexing
3
Fancy Indexing
[2 6]


Q2. Execute the 2D array Slicing.

In [20]:
import numpy as np
arr = np.array([[2,3,5],[4,5,6]])
print(arr)
print("\n",arr[1, 0:2])
print(arr[0:2,0:2])

[[2 3 5]
 [4 5 6]]

 [4 5]
[[2 3]
 [4 5]]


Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [22]:
import numpy as np
arr = np.array([1,2,3], ndmin=5)
print(arr)

[[[[[1 2 3]]]]]


Q4. Reshape the array from 1-D to 2-D array.

In [24]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
arr = arr.reshape(2,4)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [27]:
import numpy as np

arr1=np.array([1,9,5,8])
arr2=np.array([3,6,7,2])

arr_stack= np.stack((arr1,arr2))
arr_hstack= np.hstack((arr1,arr2))
arr_vstack= np.vstack((arr1,arr2))
arr_dstack= np.dstack((arr1,arr2))

print("\n",arr1)
print("\n",arr2)
print("\n",arr_stack)
print("\n",arr_hstack)
print("\n",arr_vstack)
print("\n",arr_dstack)


 [1 9 5 8]

 [3 6 7 2]

 [[1 9 5 8]
 [3 6 7 2]]

 [1 9 5 8 3 6 7 2]

 [[1 9 5 8]
 [3 6 7 2]]

 [[[1 3]
  [9 6]
  [5 7]
  [8 2]]]


Q6. Perform the searchsort method in Numpy array.

In [1]:
import numpy as np

sorted_array = np.array([1, 3, 4, 7, 9, 12])
value = 5

index_to_insert = np.searchsorted(sorted_array, value)
print(f"The value {value} should be inserted at index {index_to_insert} to maintain sorting.")

The value 5 should be inserted at index 3 to maintain sorting.


Q7. Create Numpy Structured array using your domain features.

In [3]:
import numpy as np
std_info = np.array([('jagriti jain', 23, 55.0), ('jj', 23, 59.0)],
       dtype=[('std_name', (np.str_, 10)), ('std_age', np.int32), ('std_weight', np.float64)])
 
print(std_info)

[('jagriti ja', 23, 55.) ('jj', 23, 59.)]


Q8. Create Data frame using List and Dictionary.

In [5]:
import pandas as pd
arr1=np.array([[1,2,3,4],[5,6,7,8]])
df1=pd.DataFrame(arr1)
print(df1)

print("\n")

arr2=np.array([1,2,3,4,5])
df2=pd.DataFrame(arr2)
print(df2)

arr3={"One":"tushar","Two":"shreya","Three":"Shivanshi"}
df3=pd.DataFrame(arr3,index=["One","Two","Three"])
print(df3)

   0  1  2  3
0  1  2  3  4
1  5  6  7  8


   0
0  1
1  2
2  3
3  4
4  5
          One     Two      Three
One    tushar  shreya  Shivanshi
Two    tushar  shreya  Shivanshi
Three  tushar  shreya  Shivanshi


Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [17]:
import pandas as pd

data = {
    'Flight_Number': [101, 102, 103, np.nan, 105],
    'Destination': ['New York', 'Los Angeles', np.nan, 'Houston', 'Miami'],
    'Departure_Time': ['2023-09-16 08:00', '2023-09-16 10:30', '2023-09-16 12:15', np.nan, '2023-09-16 14:45'],
    'Gate_Number': [5, 8, 3, 4, np.nan],
    'Passenger_Count': [150, 180, 0, 160, 200]
}

df = pd.DataFrame(data)
print(df)

print("\n", df.isnull())

print("\n", df.notnull())

df_dropped = df.dropna()  
print(df_dropped)

df_filled = df.fillna(0)  
print(df_filled)

df_replaced = df.replace(np.nan, -1)  
print(df_replaced)

df_interpolated = df.interpolate()  
print(df_interpolated)

   Flight_Number  Destination    Departure_Time  Gate_Number  Passenger_Count
0          101.0     New York  2023-09-16 08:00          5.0              150
1          102.0  Los Angeles  2023-09-16 10:30          8.0              180
2          103.0          NaN  2023-09-16 12:15          3.0                0
3            NaN      Houston               NaN          4.0              160
4          105.0        Miami  2023-09-16 14:45          NaN              200

    Flight_Number  Destination  Departure_Time  Gate_Number  Passenger_Count
0          False        False           False        False            False
1          False        False           False        False            False
2          False         True           False        False            False
3           True        False            True        False            False
4          False        False           False         True            False

    Flight_Number  Destination  Departure_Time  Gate_Number  Passenger_Co

C:\Users\aditi\AppData\Local\Temp\ipykernel_9812\113071181.py:27: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolated = df.interpolate()


Q10. Perform the Hierarchical Indexing in the above created dataset.

In [19]:
import pandas as pd 

data = {
    'Flight_Number': [101, 102, 103, np.nan, 105],
    'Destination': ['New York', 'Los Angeles', np.nan, 'Houston', 'Miami'],
    'Departure_Time': ['2023-09-16 08:00', '2023-09-16 10:30', '2023-09-16 12:15', np.nan, '2023-09-16 14:45'],
    'Gate_Number': [5, 8, 3, 4, np.nan],
    'Passenger_Count': [150, 180, 0, 160, 200]
}

df = pd.DataFrame(data)
print(df)

df.set_index(['Flight_Number', 'Destination'], inplace=True)
print(df)

   Flight_Number  Destination    Departure_Time  Gate_Number  Passenger_Count
0          101.0     New York  2023-09-16 08:00          5.0              150
1          102.0  Los Angeles  2023-09-16 10:30          8.0              180
2          103.0          NaN  2023-09-16 12:15          3.0                0
3            NaN      Houston               NaN          4.0              160
4          105.0        Miami  2023-09-16 14:45          NaN              200
                             Departure_Time  Gate_Number  Passenger_Count
Flight_Number Destination                                                
101.0         New York     2023-09-16 08:00          5.0              150
102.0         Los Angeles  2023-09-16 10:30          8.0              180
103.0         NaN          2023-09-16 12:15          3.0                0
NaN           Houston                   NaN          4.0              160
105.0         Miami        2023-09-16 14:45          NaN              200
